name: movie_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Network requests
  http: ^1.2.0
  
  # State management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^13.2.0
  
  # Local Database
  sqflite: ^2.3.2
  path: ^1.9.0
  
  # Efficiently cache and show images
  cached_network_image: ^3.3.1
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true